kind = "web"
previewPath = "/"
title = "Ahmed El Sayed Portfolio"
version = "1.0.0"
id = "artifacts/ahmed-portfolio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 18969
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/ahmed-portfolio run dev"

[services.env]
PORT = "18969"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/ahmed-portfolio", "run", "build"]
publicDir = "artifacts/ahmed-portfolio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
